name: Add to Roadmap

on:
  issues:
    types: [opened, transferred]

jobs:
  add:
    runs-on: ubuntu-latest
    if: vars.ROADMAP_PROJECT_URL != ''
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.ROADMAP_PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
